using System;
using System.Collections.Generic;
using System.Linq;
using LearningChannelAPI.Models;
using LearningChannelAPI.Util;
using Microsoft.Ajax.Utilities;

namespace LearningChannelAPI.DataAccess
{
	public class VideoDal
	{

		// Dados Fakes
		public static IEnumerable<Video> Videos
		{
			get
			{
				return new Video[]
				{
					new Video {Id = 1, LessonId = 1, Order = 1, NextId = 2, Progress = EnumProgress.completed, Title = "O termo estratégia ", Thumb = "http://img.youtube.com/vi/zm7jA9AhwN8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=zm7jA9AhwN8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:04", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9}, //Sources = VideoSourceDal.Sources.Where(vs => vs.VideoId == 1).ToList(), Poster = "/oceans-clip.png"
					new Video {Id = 2, LessonId = 1, Order = 2, PreviousId = 1, NextId = 3, Progress = EnumProgress.completed, Title = "Um guerreiro é estratégico ", Thumb = "http://img.youtube.com/vi/U9orH70AJUY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=U9orH70AJUY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "6:13", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 3, LessonId = 1, Order = 3, PreviousId = 2, NextId = 4, Progress = EnumProgress.completed, Title = "Habilidades-chaves da estratégia ", Thumb = "http://img.youtube.com/vi/YGXvHMYlBGM/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=YGXvHMYlBGM", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "5:03", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 4, LessonId = 1, Order = 4, PreviousId = 3, NextId = 5, Progress = EnumProgress.inProgress, Title = "Estratégia garante a subsistência", Thumb = "http://img.youtube.com/vi/s1bknQh5bzw/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=s1bknQh5bzw", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:33", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 5, LessonId = 2, Order = 1, PreviousId = 4, NextId = 6, Progress = EnumProgress.notStarted, Title = "O que é ter o espírito guerreiro?", Thumb = "http://img.youtube.com/vi/t_XSrO850_o/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=t_XSrO850_o", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:00", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 6, LessonId = 2, Order = 2, PreviousId = 5, NextId = 7, Progress = EnumProgress.notStarted, Title = "Diferença entre Meta e Propósito", Thumb = "http://img.youtube.com/vi/Tvz_SWMOZHA/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=Tvz_SWMOZHA", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:08", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 7, LessonId = 2, Order = 3, PreviousId = 6, NextId = 8, Progress = EnumProgress.inProgress, Title = "Instruções Estratégicas", Thumb = "http://img.youtube.com/vi/UYeNVJ28xzY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=UYeNVJ28xzY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:51", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 8, LessonId = 2, Order = 4, PreviousId = 7, NextId = 9, Progress = EnumProgress.completed, Title = "Equações de um Estrategista", Thumb = "http://img.youtube.com/vi/7bOVSpUcuBM/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=7bOVSpUcuBM", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:30", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 9, LessonId = 2, Order = 5, PreviousId = 8, NextId =10 , Progress = EnumProgress.notStarted, Title = "Batalhão, mostrem suas armas", Thumb = "http://img.youtube.com/vi/M6sr1FOpoaI/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=M6sr1FOpoaI", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:00", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 10, LessonId = 3, Order = 1, PreviousId = 9, NextId = 11, Progress = EnumProgress.completed, Title = "Abordagem", Thumb = "http://img.youtube.com/vi/hMt3GZ_MFbA/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=hMt3GZ_MFbA", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:33", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 11, LessonId = 3, Order = 1, PreviousId = 10, NextId = 12, Progress = EnumProgress.inProgress, Title = "Sondagem ", Thumb = "http://img.youtube.com/vi/ULZtYCjgnxQ/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=ULZtYCjgnxQ", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:16", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 12, LessonId = 3, Order = 3, PreviousId = 11, NextId = 13, Progress = EnumProgress.completed, Title = "Demonstração", Thumb = "http://img.youtube.com/vi/jqrCgTxCvFQ/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=jqrCgTxCvFQ", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:16", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 13, LessonId = 3, Order = 4, PreviousId = 12, NextId = 14, Progress = EnumProgress.completed, Title = "Superar obstáculos", Thumb = "http://img.youtube.com/vi/pvoIXpP8vU4/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=pvoIXpP8vU4", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:16", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 14, LessonId = 3, Order = 5, PreviousId = 13, NextId = 15, Progress = EnumProgress.completed, Title = "Fechamento", Thumb = "http://img.youtube.com/vi/hEffqyl_KeI/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=hEffqyl_KeI", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "3:42", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 15, LessonId = 4, Order = 1, PreviousId = 14, NextId = 16, Progress = EnumProgress.inProgress, Title = "Aparelhos que atraem os clientes ", Thumb = "http://img.youtube.com/vi/6rWqzZk6SqY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=6rWqzZk6SqY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:10", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 16, LessonId = 4, Order = 2, PreviousId = 15, Progress = EnumProgress.notStarted, Title = "Oportunidades com smatphones", Thumb = "http://img.youtube.com/vi/Z-NHiv4M2xw/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=Z-NHiv4M2xw", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:50", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 401, LessonId = 41, Order = 1, NextId = 402, Progress = EnumProgress.completed, Title = "Por que você faz parte da equipe Vivo? ", Thumb = "http://img.youtube.com/vi/zm7jA9AhwN8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=zm7jA9AhwN8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:04", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7}, //Sources = VideoSourceDal.Sources.Where(vs => vs.VideoId == 1).ToList(), Poster = "/oceans-clip.png"
					new Video {Id = 402, LessonId = 42, Order = 1, PreviousId = 401, NextId = 403, Progress = EnumProgress.completed, Title = "Imagem profissional", Thumb = "http://img.youtube.com/vi/U9orH70AJUY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=U9orH70AJUY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "6:13", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 403, LessonId = 42, Order = 2, PreviousId = 402, NextId = 404, Progress = EnumProgress.completed, Title = "O papel de cada pessoa na loja", Thumb = "http://img.youtube.com/vi/YGXvHMYlBGM/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=YGXvHMYlBGM", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "5:03", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 404, LessonId = 42, Order = 3, PreviousId = 403, NextId = 405, Progress = EnumProgress.inProgress, Title = "A trajetória do cliente", Thumb = "http://img.youtube.com/vi/s1bknQh5bzw/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=s1bknQh5bzw", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:33", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 405, LessonId = 43, Order = 1, PreviousId = 404, NextId = 406, Progress = EnumProgress.notStarted, Title = "3G Plus", Thumb = "http://img.youtube.com/vi/t_XSrO850_o/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=t_XSrO850_o", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:00", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 406, LessonId = 43, Order = 2, PreviousId = 405, NextId = 407, Progress = EnumProgress.notStarted, Title = "4G Plus", Thumb = "http://img.youtube.com/vi/Tvz_SWMOZHA/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=Tvz_SWMOZHA", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:08", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 407, LessonId = 43, Order = 3, PreviousId = 406, NextId = 408, Progress = EnumProgress.inProgress, Title = "MultiXVivo", Thumb = "http://img.youtube.com/vi/UYeNVJ28xzY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=UYeNVJ28xzY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:51", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 408, LessonId = 43, Order = 4, PreviousId = 407, NextId = 409, Progress = EnumProgress.completed, Title = "Telefone Fixo", Thumb = "http://img.youtube.com/vi/7bOVSpUcuBM/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=7bOVSpUcuBM", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:30", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 409, LessonId = 44, Order = 1, PreviousId = 408, NextId = 410 , Progress = EnumProgress.notStarted, Title = "Exemplo de atendimento com excelência", Thumb = "http://img.youtube.com/vi/M6sr1FOpoaI/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=M6sr1FOpoaI", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:00", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 410, LessonId = 44, Order = 2, PreviousId = 409, Progress = EnumProgress.completed, Title = "Que lições podemos usar no nosso atendimento?", Thumb = "http://img.youtube.com/vi/hMt3GZ_MFbA/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=hMt3GZ_MFbA", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:33", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
				};
			}
		}
	}
}