using System;
using System.Collections.Generic;
using System.Linq;
using LearningChannelAPI.Models;
using LearningChannelAPI.Util;
using Microsoft.Ajax.Utilities;

namespace LearningChannelAPI.DataAccess
{
	public class VideoDal
	{

		// Dados Fakes
		public static IEnumerable<Video> Videos
		{
			get
			{
				return new Video[]
				{
					new Video {Id = 1, LessonId = 1, Order = 1, NextId = 2, Progress = EnumProgress.completed, Title = "Mad About Jazz", Thumb = "http://img.youtube.com/vi/ZQBVDQ5KZbQ/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=ZQBVDQ5KZbQ", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:20", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9}, //Sources = VideoSourceDal.Sources.Where(vs => vs.VideoId == 1).ToList(), Poster = "/oceans-clip.png"
					new Video {Id = 2, LessonId = 1, Order = 2, PreviousId = 1, NextId = 3, Progress = EnumProgress.completed, Title = "The Tiffany Blue Book Ball", Thumb = "http://img.youtube.com/vi/KccJ6sPQ4J0/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=KccJ6sPQ4J0", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:56", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 3, LessonId = 1, Order = 3, PreviousId = 2, NextId = 4, Progress = EnumProgress.completed, Title = "Jean Schlumberger's Fish Bracelet ", Thumb = "http://img.youtube.com/vi/KjL4tGt1GOQ/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=KjL4tGt1GOQ", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:15", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 4, LessonId = 1, Order = 4, PreviousId = 3, NextId = 5, Progress = EnumProgress.inProgress, Title = "The Rare Vivid Green Diamond Ring", Thumb = "http://img.youtube.com/vi/KehlIAn27NM/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=KehlIAn27NM", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:20", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 5, LessonId = 2, Order = 1, PreviousId = 4, NextId = 6, Progress = EnumProgress.notStarted, Title = "The Deco Fan Bangle", Thumb = "http://img.youtube.com/vi/PzNQFhXQaaU/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=PzNQFhXQaaU", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:27", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 6, LessonId = 2, Order = 2, PreviousId = 5, NextId = 7, Progress = EnumProgress.notStarted, Title = "The Dream Maker [Trailer]", Thumb = "http://img.youtube.com/vi/rRyVFPJHX0Q/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=rRyVFPJHX0Q", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:01", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 7, LessonId = 2, Order = 3, PreviousId = 6, NextId = 8, Progress = EnumProgress.inProgress, Title = "Louis Comfort Tiffany", Thumb = "http://img.youtube.com/vi/6QxSZVVDVE8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=6QxSZVVDVE8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:52", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 8, LessonId = 2, Order = 4, PreviousId = 7, NextId = 9, Progress = EnumProgress.completed, Title = "The Genius of Jean Schlumberger", Thumb = "http://img.youtube.com/vi/q8WKzWRzzao/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=q8WKzWRzzao", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:53", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 9, LessonId = 2, Order = 5, PreviousId = 8, NextId =10 , Progress = EnumProgress.notStarted, Title = "The Dream Maker", Thumb = "http://img.youtube.com/vi/M286DFVJx5s/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=M286DFVJx5s", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:51", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 10, LessonId = 3, Order = 1, PreviousId = 9, NextId = 11, Progress = EnumProgress.completed, Title = "The Tiffany Soho Mural by Danielle Dimston", Thumb = "http://img.youtube.com/vi/F9Ow3JIAKR8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=F9Ow3JIAKR8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "6:33", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 11, LessonId = 3, Order = 1, PreviousId = 10, NextId = 12, Progress = EnumProgress.inProgress, Title = "The Tiffany & Co. Soho Artist Series", Thumb = "http://img.youtube.com/vi/9j2jU-2Iu8Y/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=9j2jU-2Iu8Y", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:36", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 12, LessonId = 3, Order = 3, PreviousId = 11, NextId = 13, Progress = EnumProgress.completed, Title = "The Tiffany Soho Mural by Natasha Law", Thumb = "http://img.youtube.com/vi/vlHdrOlfz7U/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=vlHdrOlfz7U", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "4:19", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 13, LessonId = 3, Order = 4, PreviousId = 12, NextId = 14, Progress = EnumProgress.completed, Title = "Paloma's Dove", Thumb = "http://img.youtube.com/vi/k2ZmXI9MRUo/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=k2ZmXI9MRUo", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:06", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 14, LessonId = 3, Order = 5, PreviousId = 13, NextId = 15, Progress = EnumProgress.completed, Title = "Paloma's Charms", Thumb = "http://img.youtube.com/vi/6wN8F3IboIw/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=6wN8F3IboIw", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:16", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 15, LessonId = 4, Order = 1, PreviousId = 14, NextId = 16, Progress = EnumProgress.inProgress, Title = "Love Comes Into the Picture", Thumb = "http://img.youtube.com/vi/ry_5NcTeloA/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=ry_5NcTeloA", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "2:27", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 16, LessonId = 4, Order = 2, PreviousId = 15, Progress = EnumProgress.notStarted, Title = "The One and Only Tiffany Diamond", Thumb = "http://img.youtube.com/vi/O5zJ1KK3AC8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=O5zJ1KK3AC8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:48", Width = 640, Height = 360, VideosCount = 16, VideosCompleted = 9},
					new Video {Id = 401, LessonId = 41, Order = 1, NextId = 402, Progress = EnumProgress.completed, Title = "Paloma's Venezia—Luce", Thumb = "http://img.youtube.com/vi/90KaRUdRNic/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=90KaRUdRNic", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:40", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7}, //Sources = VideoSourceDal.Sources.Where(vs => vs.VideoId == 1).ToList(), Poster = "/oceans-clip.png"
					new Video {Id = 402, LessonId = 42, Order = 1, PreviousId = 401, NextId = 403, Progress = EnumProgress.completed, Title = "Paloma's Venezia—Stella", Thumb = "http://img.youtube.com/vi/bIOgCasoZkg/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=bIOgCasoZkg", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:48", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 403, LessonId = 42, Order = 2, PreviousId = 402, NextId = 404, Progress = EnumProgress.completed, Title = "Paloma Picasso & Tiffany", Thumb = "http://img.youtube.com/vi/Zqq9IkewfHE/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=Zqq9IkewfHE", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:43", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 404, LessonId = 42, Order = 3, PreviousId = 403, NextId = 405, Progress = EnumProgress.inProgress, Title = "Capturing The Light Of Dawn", Thumb = "http://img.youtube.com/vi/L58reVa_uFg/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=L58reVa_uFg", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:21", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 405, LessonId = 43, Order = 1, PreviousId = 404, NextId = 406, Progress = EnumProgress.notStarted, Title = "The Tiffany Soho Mural by Ellis Gallagher", Thumb = "http://img.youtube.com/vi/BgpzJ5Py7A8/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=BgpzJ5Py7A8", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "5:26", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 406, LessonId = 43, Order = 2, PreviousId = 405, NextId = 407, Progress = EnumProgress.notStarted, Title = "The Tiffany Soho Mural by Danny Roberts", Thumb = "http://img.youtube.com/vi/ACKg-ZQH2ow/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=ACKg-ZQH2ow", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "5:37", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 407, LessonId = 43, Order = 3, PreviousId = 406, NextId = 408, Progress = EnumProgress.inProgress, Title = "The Tiffany® Setting", Thumb = "http://img.youtube.com/vi/3HOVVXdU_w0/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=3HOVVXdU_w0", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "0:36", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
					new Video {Id = 408, LessonId = 43, Order = 4, PreviousId = 407, Progress = EnumProgress.completed, Title = "The King of Diamonds", Thumb = "http://img.youtube.com/vi/nldJ1KbbjMY/2.jpg", Type = VideoType.Youtube, Url = "http://www.youtube.com/watch?v=nldJ1KbbjMY", Description="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", Duration= "1:00", Width = 640, Height = 360, VideosCount = 10, VideosCompleted = 7},
				};
			}
		}
	}
}